export const WORKER_DETAILS_ADDED = 'WORKER_DETAILS_ADDED';

export const MAIN_SCREEN_ITEMS_LOADING = 'MAIN_SCREEN_ITEMS_LOADING';
export const MAIN_SCREEN_ITEMS_SUCCESS = 'MAIN_SCREEN_ITEMS_SUCCESS';
export const MAIN_SCREEN_ITEMS_EMPTY_SUCCESS = 'MAIN_SCREEN_ITEMS_EMPTY_SUCCESS';
export const MAIN_SCREEN_ITEMS_ERROR = 'MAIN_SCREEN_ITEMS_ERROR';

export const REGISTER_SCREEN_LOADING = 'REGISTER_SCREEN_LOADING';
export const REGISTER_SCREEN_SUCCESS = 'REGISTER_SCREEN_SUCCESS';
export const REGISTER_SCREEN_ERROR = 'REGISTER_SCREEN_ERROR';
